config/routes.rb
Rails.application.routes.draw do
  # get "tweets", to: "tweets#index"
  get 'crypto-news', to: 'pages#crypto_feed'
  namespace :users do
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  resources :tweets, only: [:new, :index, :create, :update]
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  #validates :user_id, presence: true
  # validates :body, presence: true, length: { maximum: 280 }
  before_create :post_to_twitter

  # def initialize(params={body: 'nil'})
  #   @tweet = Tweet.new(params)
  # end

  def post_to_twitter(msg)
    SocialTool.update(msg)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :timeoutable, :omniauthable, omniauth_providers: [:twitter]

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do | user |
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = provider_data.info.nickname
      user.image = provider_data.info.image
      user.description = provider_data.info.description
      user.skip_confirmation!
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @history = SocialTool.user_timeline(200)
  end

  def crypto_feed
    @crypto_tweets = SocialTool.crypto_news
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new]

  def index
  end

  def new
    @tweet = Tweet.new
    # @tweet = Tweet.create(tweet_params)
    # @tweet.post_to_twitter(tweet_params[:body])
    # if tweet_params[:tweet][:body].present?
    if tweet_params[:body].present?
      @tweet.post_to_twitter(tweet_params[:body])
      redirect_to root_path, notice: 'Your soon to be viral tweet has been posted! Noice!!'
    end
  end

  # def create
  #   @tweet = Tweet.create(tweet_params, user_id: current_user.id)
  #   # @tweet.user_id = current_user.id
  #   if @tweet.save
  #     redirect_to root_path, notice: 'Your tweet will definitely go viral! Noice!!'
  #   else
  #     render 'new'
  #   end
  #   respond_with(@tweet)
  # end

  def update
    if tweet_params[:body].present?
      @tweet.post_to_twitter(tweet_params[:body])
    end
    respond_with(@tweet)
  end

  private

  def tweet_params
    params.permit(:body)
    # params.require(:tweet).permit(:body)
  end
end

app/controllers/users/omniauth_controller.rb
class Users::OmniauthController < ApplicationController
  # twitter callback
  def twitter
    @user = User.create_from_provider_data(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user#, event: :authentication
      flash[:success] if is_navigational_format?
    else
      flash[:error] = 'There was a hiccup signing you in through Twitter. Please
                      register or try signing in later.'
      redirect_to new_user_registration_url
    end
  end

  # fallback for the callback...
  def failure
    flash[:error] = "Yikes! There was a problem signing you in. Please register
                    or try signing in later."
    redirect_to new_user_registration_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users/omniauth_helper.rb
module Users::OmniauthHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
  <%= link_to "Coinmine Canary", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav justify-content-end" id="navbarLinks">
      <li class="nav-item">
        <%= link_to "Post a Tweet", new_tweet_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Crypto News", crypto_news_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li><%= link_to 'Sign out', destroy_user_session_path, class: 'nav-link', method: :delete %></li>
      <% else %>
        <li><%= link_to 'Log in', new_user_session_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoinmineCanary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>


    <%= yield %>
  </body>
</html>

app/views/pages/crypto_feed.html.erb
<br>
<h1 class="pageTitle">Pages#crypto_news</h1>
<br>
<section class="container">
  <p>Find me in app/views/pages/crypto_news.html.erb</p>

  <ol>
    <%= @crypto_tweets.each do |tweet| %>
      <li>
        <%= tweet %>
      </li>
      <br>
    <% end %>
  </ol>
</section>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<ul>
  <%= @history.each do |tweet| %>
    <li>
      <%= tweet.text %>
    </li>
    <br>
  <% end %>
</ul>

app/views/tweets/_form.html.erb
<form>
  <%= form_for(@tweet) do |f| %>
    <% if @tweet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tweet.errors.count, "error") %> kept this tweet from being posted</h2>
        <ul>
          <% @tweet.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <section class="actions"%>
      <%= f.submit "Post", class: 'btn-info'%>
    </section>
  <% end %>
</form>

app/views/tweets/index.html.erb
<h1>Coinmine Canary</h1>

app/views/tweets/new.html.erb
<br>
<h1 class="pageTitle">Post a New Tweet</h1>
<br>
<section class="container">
  <%= render 'tweets/form' %>
</section>